export const BUY_PRODUCT = "BUY_PRODUCT";
export const CHANGE_NOTIFY = "CHANGE_NOTIFY";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const QUANTITY_DOWN = "QUANTITY_DOWN";
export const QUANTITY_UP = "QUANTITY_UP";