export const ADD_STUDENT = "ADD_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const CHANGE_NOTIFY = "CHANGE_NOTIFY";
export const GET_DATA = "GET_DATA";